"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.fakeProducts = void 0;
exports.fakeProducts = [
    // Men's Fashion - New Arrivals
    {
        name: "Casual Linen Shirt",
        brand: "Levis",
        price: 85,
        images: [
            "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1602810318660-d2c46b09d6a9?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Comfortable casual linen shirt perfect for everyday wear. Breathable fabric with a relaxed fit.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "White", "Navy"],
        tags: ["casual", "summer", "lightweight"],
        rating: 4.5,
        reviews: 3200,
        inStock: true,
    },
    {
        name: "Premium Denim Jacket",
        brand: "Wrangler",
        price: 125,
        images: [
            "https://images.unsplash.com/photo-1551028719-2ca1b8e4e5f2?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1576871337632-b9aef4c17ab9?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Classic denim jacket with modern fit. Made from premium denim with brass hardware.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals", "best-sellers"],
        sizes: ["M", "L", "XL"],
        colors: ["Dark Blue", "Light Blue", "Black"],
        tags: ["denim", "jacket", "classic"],
        rating: 5,
        reviews: 5100,
        inStock: true,
    },
    {
        name: "Wool Blend Sweater",
        brand: "H&M",
        price: 75.5,
        images: [
            "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1620799140408-eec2d0d3c0ed?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Warm and cozy wool blend sweater. Perfect for cold weather with a classic crew neck design.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Gray", "Navy", "Burgundy"],
        tags: ["sweater", "winter", "warm"],
        rating: 4,
        reviews: 2800,
        inStock: true,
    },
    {
        name: "Corduroy Button Shirt",
        brand: "Gap",
        price: 69,
        images: [
            "https://images.unsplash.com/photo-1602810319428-019690571b5b?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Soft corduroy shirt with button-down collar. Vintage-inspired design with modern fit.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Brown", "Green", "Navy"],
        tags: ["corduroy", "vintage", "casual"],
        rating: 4.2,
        reviews: 1100,
        inStock: true,
    },
    {
        name: "Slim Fit Chinos",
        brand: "Uniqlo",
        price: 49,
        images: [
            "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Versatile slim fit chinos for any occasion. Comfortable stretch fabric with modern silhouette.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals", "best-sellers"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Beige", "Navy", "Olive", "Black"],
        tags: ["chinos", "pants", "versatile"],
        rating: 4.4,
        reviews: 900,
        inStock: true,
    },
    {
        name: "Lightweight Hoodie",
        brand: "Nike",
        price: 79,
        images: [
            "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1620799139834-6b8f844fbe61?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Athletic lightweight hoodie with moisture-wicking technology. Perfect for workouts or casual wear.",
        category: "mens-fashion",
        collections: ["all-products", "new-arrivals", "best-sellers"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Gray", "Black", "Navy"],
        tags: ["athletic", "hoodie", "sportswear"],
        rating: 4.6,
        reviews: 2300,
        inStock: true,
    },
    // Women's Fashion - New Arrivals
    {
        name: "Elegant Satin Dress",
        brand: "Al Karam",
        price: 95.5,
        images: [
            "https://images.unsplash.com/photo-1566174053879-31528523f8ae?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Stunning satin dress with elegant drape. Perfect for special occasions and evening events.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Navy", "Burgundy"],
        tags: ["dress", "elegant", "evening"],
        rating: 5,
        reviews: 4100,
        inStock: true,
    },
    {
        name: "Maxi Floral Dress",
        brand: "Al Karam",
        price: 95.5,
        images: [
            "https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Beautiful long maxi dress with floral print. Flowing silhouette perfect for summer days.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Floral Blue", "Floral Pink", "Floral White"],
        tags: ["maxi", "floral", "summer"],
        rating: 5,
        reviews: 4100,
        inStock: true,
    },
    {
        name: "Cozy Knit Sweater",
        brand: "Al Karam",
        price: 95.5,
        images: [
            "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Soft and cozy knit sweater. Oversized fit perfect for layering during cooler months.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Cream", "Gray", "Camel"],
        tags: ["sweater", "cozy", "winter"],
        rating: 5,
        reviews: 4100,
        inStock: true,
    },
    {
        name: "Floral Midi Dress",
        brand: "Zara",
        price: 79,
        images: [
            "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1562157873-818bc0726f68?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Charming midi dress with delicate floral pattern. Feminine silhouette with gathered waist.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Floral Print", "White"],
        tags: ["midi", "floral", "feminine"],
        rating: 4.5,
        reviews: 1900,
        inStock: true,
    },
    {
        name: "Silk Blouse",
        brand: "COS",
        price: 68,
        images: [
            "https://images.unsplash.com/photo-1564257577149-47f1cc08c6d6?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1588117305388-c2631a279f82?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Luxurious silk blouse with relaxed fit. Versatile piece for work or casual occasions.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L"],
        colors: ["White", "Black", "Blush"],
        tags: ["silk", "blouse", "elegant"],
        rating: 4.7,
        reviews: 2200,
        inStock: true,
    },
    {
        name: "Pleated Midi Skirt",
        brand: "Mango",
        price: 59,
        images: [
            "https://images.unsplash.com/photo-1583846832232-c120d3023e1c?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Elegant pleated midi skirt. Timeless design that pairs well with any top.",
        category: "womens-fashion",
        collections: ["all-products", "new-arrivals"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Navy", "Gray"],
        tags: ["skirt", "pleated", "classic"],
        rating: 4.3,
        reviews: 1400,
        inStock: true,
    },
    // Women's Accessories
    {
        name: "Leather Tote Bag",
        brand: "Michael Kors",
        price: 145,
        images: [
            "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Spacious leather tote bag with multiple compartments. Perfect for work or travel.",
        category: "womens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Brown", "Tan"],
        tags: ["bag", "leather", "tote"],
        rating: 5,
        reviews: 5300,
        inStock: true,
    },
    {
        name: "Gold Chain Necklace",
        brand: "Pandora",
        price: 89,
        images: [
            "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Delicate gold chain necklace. Timeless piece that adds elegance to any outfit.",
        category: "womens-accessories",
        collections: ["all-products", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Gold"],
        tags: ["jewelry", "necklace", "gold"],
        rating: 4.5,
        reviews: 2900,
        inStock: true,
    },
    {
        name: "Silk Printed Scarf",
        brand: "Hermès",
        price: 120,
        images: [
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1611652022419-a9419f74343a?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Luxurious silk scarf with artistic print. Versatile accessory that elevates any look.",
        category: "womens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Multicolor", "Navy", "Red"],
        tags: ["scarf", "silk", "luxury"],
        rating: 5,
        reviews: 3700,
        inStock: true,
    },
    {
        name: "Aviator Sunglasses",
        brand: "Ray-Ban",
        price: 129,
        images: [
            "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1574169208507-84376144848b?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Classic aviator sunglasses with UV protection. Iconic style that never goes out of fashion.",
        category: "womens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Gold Frame", "Silver Frame"],
        tags: ["sunglasses", "aviator", "classic"],
        rating: 4.4,
        reviews: 1200,
        inStock: true,
    },
    {
        name: "Beaded Bracelet Set",
        brand: "Tiffany",
        price: 49,
        images: [
            "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Elegant beaded bracelet set. Mix and match for a personalized look.",
        category: "womens-accessories",
        collections: ["all-products", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Silver", "Gold", "Rose Gold"],
        tags: ["bracelet", "jewelry", "beaded"],
        rating: 4.2,
        reviews: 900,
        inStock: true,
    },
    {
        name: "Evening Clutch",
        brand: "Kate Spade",
        price: 99,
        images: [
            "https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Chic evening clutch with chain strap. Perfect for formal events and parties.",
        category: "womens-accessories",
        collections: ["all-products", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Gold", "Silver"],
        tags: ["clutch", "evening", "formal"],
        rating: 4.6,
        reviews: 1700,
        inStock: true,
    },
    // Men's Accessories
    {
        name: "Leather Belt",
        brand: "Gucci",
        price: 125,
        images: [
            "https://images.unsplash.com/photo-1624222247344-550fb60583dc?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Premium leather belt with signature buckle. Essential accessory for any wardrobe.",
        category: "mens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Brown"],
        tags: ["belt", "leather", "luxury"],
        rating: 5,
        reviews: 4500,
        inStock: true,
    },
    {
        name: "Classic Automatic Watch",
        brand: "Rolex",
        price: 350,
        images: [
            "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Luxury automatic watch with sapphire crystal. Investment piece that lasts a lifetime.",
        category: "mens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Silver", "Gold"],
        tags: ["watch", "luxury", "automatic"],
        rating: 5,
        reviews: 7200,
        inStock: true,
    },
    {
        name: "Leather Bifold Wallet",
        brand: "Louis Vuitton",
        price: 95,
        images: [
            "https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1591561954555-607968c989ab?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Sleek leather bifold wallet with multiple card slots. Compact yet spacious design.",
        category: "mens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Brown", "Navy"],
        tags: ["wallet", "leather", "bifold"],
        rating: 4.5,
        reviews: 5100,
        inStock: true,
    },
    {
        name: "Silver Cufflinks Set",
        brand: "Tiffany",
        price: 69,
        images: [
            "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1513135065346-a098a63a71ee?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Elegant silver cufflinks set. Perfect finishing touch for formal attire.",
        category: "mens-accessories",
        collections: ["all-products", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Silver", "Gold"],
        tags: ["cufflinks", "formal", "silver"],
        rating: 4.3,
        reviews: 800,
        inStock: true,
    },
    {
        name: "Polarized Sunglasses",
        brand: "Persol",
        price: 149,
        images: [
            "https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Premium polarized sunglasses with UV protection. Italian craftsmanship and style.",
        category: "mens-accessories",
        collections: ["all-products", "accessories", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Tortoise", "Blue"],
        tags: ["sunglasses", "polarized", "luxury"],
        rating: 4.6,
        reviews: 1300,
        inStock: true,
    },
    {
        name: "Silk Pocket Square",
        brand: "Hermès",
        price: 39,
        images: [
            "https://images.unsplash.com/photo-1621186403033-8cffaef1e104?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Luxurious silk pocket square. Adds sophistication to any suit or blazer.",
        category: "mens-accessories",
        collections: ["all-products", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Navy", "Burgundy", "Gray"],
        tags: ["pocket square", "silk", "formal"],
        rating: 4.1,
        reviews: 460,
        inStock: true,
    },
    // Discount Deals
    {
        name: "Summer Floral Dress",
        brand: "Zara",
        price: 45,
        images: [
            "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Light and breezy summer dress with floral print. Perfect for warm weather days.",
        category: "womens-fashion",
        collections: ["all-products", "discount-deals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Floral", "White"],
        tags: ["summer", "dress", "sale"],
        rating: 4.5,
        reviews: 3800,
        inStock: true,
    },
    {
        name: "Basic Cotton T-Shirt",
        brand: "H&M",
        price: 25,
        images: [
            "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1562087089-5e1c0c1ca6ff?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Essential cotton t-shirt. Soft fabric and classic fit for everyday wear.",
        category: "mens-fashion",
        collections: ["all-products", "discount-deals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Black", "Gray", "Navy"],
        tags: ["basic", "tshirt", "cotton"],
        rating: 4,
        reviews: 5500,
        inStock: true,
    },
    {
        name: "Classic Denim Jeans",
        brand: "Levis",
        price: 55,
        images: [
            "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1582552938357-32b906df40cb?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Timeless denim jeans with straight leg fit. Durable and comfortable for all-day wear.",
        category: "mens-fashion",
        collections: ["all-products", "discount-deals", "best-sellers"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Blue", "Black", "Light Wash"],
        tags: ["jeans", "denim", "classic"],
        rating: 5,
        reviews: 6700,
        inStock: true,
    },
    {
        name: "Running Sneakers",
        brand: "Adidas",
        price: 69,
        images: [
            "https://images.unsplash.com/photo-1460353581641-37baddab0fa2?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Lightweight running sneakers with cushioned sole. Perfect for workouts or casual wear.",
        category: "mens-accessories",
        collections: ["all-products", "discount-deals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Black", "Red"],
        tags: ["sneakers", "running", "athletic"],
        rating: 4.6,
        reviews: 2100,
        inStock: true,
    },
    {
        name: "Graphic Print Tee",
        brand: "Uniqlo",
        price: 19,
        images: [
            "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1562087089-5e1c0c1ca6ff?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Trendy graphic print t-shirt. Comfortable cotton blend with eye-catching design.",
        category: "mens-fashion",
        collections: ["all-products", "discount-deals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "White", "Navy"],
        tags: ["graphic", "tshirt", "trendy"],
        rating: 4.2,
        reviews: 1900,
        inStock: true,
    },
    {
        name: "Casual Shorts",
        brand: "Forever21",
        price: 15,
        images: [
            "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1603252109303-2751441dd157?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Comfortable casual shorts perfect for summer. Lightweight fabric with elastic waist.",
        category: "mens-fashion",
        collections: ["all-products", "discount-deals"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Khaki", "Navy", "Black"],
        tags: ["shorts", "summer", "casual"],
        rating: 4.0,
        reviews: 700,
        inStock: true,
    },
    // Additional Best Sellers
    {
        name: "Leather Jacket",
        brand: "AllSaints",
        price: 299,
        images: [
            "https://images.unsplash.com/photo-1551028719-2ca1b8e4e5f2?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1520975954732-35dd22299614?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Premium leather jacket with quilted lining. Timeless piece that ages beautifully.",
        category: "mens-fashion",
        collections: ["all-products", "best-sellers"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Brown"],
        tags: ["leather", "jacket", "premium"],
        rating: 4.8,
        reviews: 3400,
        inStock: true,
    },
    {
        name: "Wool Coat",
        brand: "Zara",
        price: 189,
        images: [
            "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1544923246-77307dd654d3?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Elegant wool coat for cold weather. Classic double-breasted design with notched lapels.",
        category: "womens-fashion",
        collections: ["all-products", "best-sellers"],
        sizes: ["S", "M", "L"],
        colors: ["Black", "Camel", "Gray"],
        tags: ["coat", "wool", "winter"],
        rating: 4.7,
        reviews: 2800,
        inStock: true,
    },
    {
        name: "Cashmere Scarf",
        brand: "Burberry",
        price: 175,
        images: [
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1520903920243-00d872a2d1c9?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Luxurious cashmere scarf with signature check pattern. Soft and warm for winter.",
        category: "womens-accessories",
        collections: ["all-products", "best-sellers", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Classic Check", "Navy", "Black"],
        tags: ["scarf", "cashmere", "luxury"],
        rating: 4.9,
        reviews: 4200,
        inStock: true,
    },
    {
        name: "Chelsea Boots",
        brand: "Dr. Martens",
        price: 159,
        images: [
            "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1542840410-3092f99611a3?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Iconic Chelsea boots with durable leather. Classic style meets modern comfort.",
        category: "mens-accessories",
        collections: ["all-products", "best-sellers", "accessories"],
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Brown"],
        tags: ["boots", "chelsea", "leather"],
        rating: 4.6,
        reviews: 3900,
        inStock: true,
    },
    {
        name: "Silk Tie",
        brand: "Hugo Boss",
        price: 59,
        images: [
            "https://images.unsplash.com/photo-1589756823695-278bc00c756e?auto=format&fit=crop&w=800&q=60",
            "https://images.unsplash.com/photo-1611735341450-74d61e660ad2?auto=format&fit=crop&w=800&q=60",
        ],
        description: "Elegant silk tie perfect for business or formal occasions. Smooth texture and refined pattern.",
        category: "mens-accessories",
        collections: ["all-products", "best-sellers", "accessories"],
        sizes: ["S", "M", "L"],
        colors: ["Navy", "Burgundy", "Gray", "Black"],
        tags: ["tie", "silk", "formal"],
        rating: 4.4,
        reviews: 1600,
        inStock: true,
    },
];
